### ISSUE TITLE
DeepPhys

### ISSUE THREAD

**Issue by qfei97** [terbed/Deep-rPPG#5]
Hello, In the process of reproducing DeepPhys according to your code, I found the experimental results were poor. Did you also meet them

**Comment by terbed** [comment]
What do you mean when you say "the experimental results were poor". I trained it on a limited amount of data and it performed pretty well.

**Comment by wokanmanhua** [comment]
When you train with deepphys, will the loss of training be almost the same? It looks like there's no training at all

**Comment by terbed** [comment]
You shall see some improvement (though not major).Here is an example:
https://www.comet.ml/terbed/deepphys/4635d169a63e4e0ca1ef98d6f89c6e0c?experiment-tab=chart&showOutliers=true&smoothing=0&transformY=smoothing&viewId=qI20NJSigf7tYED7VpBzVTw5a&xAxis=step

**Comment by wokanmanhua** [comment]
Is this MSEloss?

**Comment by terbed** [comment]
L1 based on this: https://www.comet.ml/terbed/deepphys/4635d169a63e4e0ca1ef98d6f89c6e0c?experiment-tab=params&viewId=qI20NJSigf7tYED7VpBzVTw5a

**Comment by wokanmanhua** [comment]
Excuse me, do you use the difference between adjacent signal points of two rPPG trace as the training label? If so, is this also used as a label for calculating MAE?

**Comment by terbed** [comment]
Please read the official DeepPhys article for more information, I followed the steps written there. So to answer your question, MAE is calculated between the network's output and the derivative of the reference signal.

**Comment by wokanmanhua** [comment]
> Please read the official DeepPhys article for more information, I followed the steps written there. So to answer your question, MAE is calculated between the network's output and the derivative of the reference signal.

I don't think so. If you look at the paper, the unit behind MAE is BPM, so it is possible to calculate MAE by heart rate instead of derivative of the reference signal.
